In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3
# import sklearn

# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import StandardScaler
# from sklearn.linear_model import LinearRegression
# from sklearn.tree import DecisionTreeClassifier
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# import tensorflow as tf
# from tensorflow import keras

# import statsmodels.api as sm

import warnings
warnings.filterwarnings("ignore")

pd.set_option('display.max_columns', None)

In [2]:
conn = sqlite3.connect('NBA-Boxscore-Database.sqlite')

In [3]:
query = 'SELECT * from game_info'
game_info = pd.read_sql(query, con=conn)
game_info

,game_id,season,date,away_team,away_score,home_team,home_score,result
0,131410290001,1314,2013-10-29,ORL,87,IND,97,1
1,131410290002,1314,2013-10-29,CHI,95,MIA,107,1
2,131410290003,1314,2013-10-29,LAC,103,LAL,116,1
3,131410300004,1314,2013-10-30,BRK,94,CLE,98,1
4,131410300005,1314,2013-10-30,BOS,87,TOR,93,1
...,...,...,...,...,...,...,...,...
11974,222304091226,2223,2023-04-09,UTA,117,LAL,128,1
11975,222304091227,2223,2023-04-09,NOP,108,MIN,113,1
11976,222304091228,2223,2023-04-09,MEM,100,OKC,115,1
11977,222304091229,2223,2023-04-09,LAC,119,PHO,114,0
11978,222304091230,2223,2023-04-09,GSW,157,POR,101,0

In [4]:
query = 'SELECT * from player_stats'
player_stats = pd.read_sql(query, con=conn)
player_stats

,game_id,player,team,MP,FG,FGA,FGp,3P,3PA,3Pp,FT,FTA,FTp,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,PM,TSp,eFGp,3PAr,FTr,ORBp,DRBp,TRBp,ASTp,STLp,BLKp,TOVp,USGp,ORtg,DRtg,BPM,PIE
0,131410290001,Arron Afflalo,ORL,32:59,3.0,14.0,0.214,1.0,5.0,0.200,2.0,3.0,0.667,1.0,2.0,3.0,1.0,0.0,0.0,1.0,1.0,9.0,-14.0,0.294,0.250,0.357,0.214,3.1,8.1,5.3,4.6,0.0,0.0,6.1,20.8,69.0,111.0,-9.9,-1.1
1,131410290001,Nikola Vučević,ORL,30:39,4.0,11.0,0.364,0.0,0.0,NaN,0.0,0.0,NaN,5.0,5.0,10.0,3.0,2.0,1.0,5.0,4.0,8.0,-22.0,0.364,0.364,0.000,0.000,16.7,21.8,18.9,15.8,3.3,2.9,31.3,21.9,70.0,98.0,-5.4,3.8
2,131410290001,Jameer Nelson,ORL,30:34,4.0,13.0,0.308,3.0,7.0,0.429,1.0,1.0,1.000,1.0,4.0,5.0,7.0,2.0,0.0,2.0,1.0,12.0,-11.0,0.446,0.423,0.538,0.077,3.3,17.4,9.5,37.0,3.3,0.0,13.0,21.2,102.0,101.0,5.9,10.3
3,131410290001,Jason Maxiell,ORL,26:19,0.0,5.0,0.000,0.0,0.0,NaN,0.0,0.0,NaN,1.0,4.0,5.0,0.0,1.0,2.0,2.0,2.0,0.0,-15.0,0.000,0.000,0.000,0.000,3.9,20.3,11.0,0.0,1.9,6.8,28.6,11.2,8.0,99.0,-10.6,-1.9
4,131410290001,Maurice Harkless,ORL,23:30,6.0,13.0,0.462,2.0,2.0,1.000,0.0,1.0,0.000,1.0,0.0,1.0,0.0,1.0,0.0,0.0,4.0,14.0,-3.0,0.521,0.538,0.154,0.077,4.3,0.0,2.5,0.0,2.2,0.0,0.0,24.0,111.0,107.0,2.4,2.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305727,222304091230,John Butler,POR,22:01,1.0,5.0,0.200,1.0,3.0,0.333,0.0,0.0,NaN,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,3.0,-37.0,0.300,0.300,0.600,0.000,0.0,6.6,2.5,0.0,0.0,0.0,0.0,9.1,58.0,149.0,-14.6,-0.7
305728,222304091230,Chance Comanche,POR,20:47,3.0,5.0,0.600,0.0,0.0,NaN,1.0,4.0,0.250,2.0,1.0,3.0,0.0,0.0,1.0,0.0,0.0,7.0,-29.0,0.518,0.600,0.000,0.800,8.4,7.0,7.9,0.0,0.0,4.9,0.0,13.1,110.0,146.0,-7.6,1.7
305729,222304091230,Jabari Walker,POR,20:44,4.0,6.0,0.667,0.0,2.0,0.000,1.0,2.0,0.500,0.0,3.0,3.0,0.0,0.0,0.0,2.0,0.0,9.0,-29.0,0.654,0.667,0.333,0.333,0.0,21.0,7.9,0.0,0.0,0.0,22.5,17.2,89.0,147.0,-9.8,2.6
305730,222304091230,Drew Eubanks,POR,Did Not Dress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305731,222304091230,Cam Reddish,POR,Did Not Dress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# player, SUM(FG), SUM(FGA), SUM(FT), SUM(FTA), SUM("3P"), SUM(ORBp), SUM(TOV)

game_id = 222304091230
query = f'''select player, SUM(FG) as FG, SUM(FGA) as FGA, SUM(FT) as FT, SUM(FTA) as FTA, SUM("3P") as P3, SUM(ORBp) as ORBp, SUM(TOV) as TOV
from ( select ROW_NUMBER() OVER (PARTITION BY d.player order by d.date desc ) r, d.*  
    from ( select game_id, player from player_stats ps where ps.game_id={game_id} ) gs
    inner join ( select b.date,  a.* from player_stats a inner join game_info b on a.game_id = b.game_id ) d
        on gs.player=d.player
) k
where (k.r BETWEEN 2 and 11)
group by player;'''

ss = pd.read_sql(query, con=conn)

In [9]:
game_id = 131410290001
query = f'''select player, SUM(FG) as FG, SUM(FGA) as FGA, SUM(FT) as FT, SUM(FTA) as FTA, SUM("3P") as P3, SUM(ORBp) as ORBp, SUM(TOV) as TOV
from ( select ROW_NUMBER() OVER (PARTITION BY d.player order by d.date desc ) r, d.*  
    from ( select game_id, player from player_stats ps where ps.game_id={game_id} ) gs
    inner join ( select b.date,  a.* from player_stats a inner join game_info b on a.game_id = b.game_id ) d
        on gs.player=d.player
) k
where (k.r BETWEEN 2 and 11)
group by player;'''

ff = pd.read_sql(query, con=conn)

In [10]:
ff

              player    FG    FGA    FT   FTA    P3   ORBp   TOV
0   Andrew Nicholson   4.0    9.0   0.0   0.0   0.0    0.0   2.0
1      Arron Afflalo   3.0   10.0   2.0   2.0   2.0    0.0   1.0
2        C.J. Watson   8.0   29.0   3.0   4.0   1.0   23.4   6.0
3     Chris Copeland   1.0    5.0   2.0   2.0   1.0    0.0   1.0
4         David West  26.0   54.0   9.0  11.0   0.0   56.6   7.0
5       Donald Sloan  23.0   50.0  11.0  15.0   5.0    4.3   9.0
6         Doron Lamb  17.0   35.0  11.0  15.0  12.0    9.1   9.0
7      E'Twaun Moore  12.0   15.0   2.0   2.0   3.0    5.2   4.0
8        George Hill   3.0    6.0   4.0   4.0   1.0    6.5   1.0
9        Ian Mahinmi   NaN    NaN   NaN   NaN   NaN    NaN   NaN
10     Jameer Nelson   0.0    5.0   0.0   0.0   0.0    0.0   0.0
11     Jason Maxiell  20.0   40.0   2.0   4.0   0.0  140.5   8.0
12      Kyle O'Quinn   4.0    8.0   1.0   1.0   0.0    3.4   1.0
13  Lance Stephenson  34.0   69.0  17.0  18.0  10.0    8.6  17.0
14        Luis Scola   0.0    5.0   1.0   2.0   0.0   16.6   1.0
15  Maurice Harkless   0.0    0.0   0.0   0.0   0.0    0.0   0.0
16    Nikola Vučević  76.0  128.0  17.0  19.0   9.0   55.8  16.0
17   Orlando Johnson   9.0   34.0   6.0   8.0   2.0   13.8   4.0
18       Paul George  85.0  196.0  64.0  71.0  23.0   39.3  25.0
19     Rasual Butler  13.0   24.0   3.0   5.0   3.0   17.8   2.0
20      Ronnie Price   1.0   16.0   3.0   4.0   1.0   23.9   1.0
21       Roy Hibbert   0.0    0.0   0.0   0.0   0.0    0.0   1.0
22      Solomon Hill   1.0    9.0   0.0   0.0   0.0   22.7   0.0
23     Solomon Jones   0.0    2.0   0.0   0.0   0.0   40.4   0.0
24     Tobias Harris  57.0  100.0  19.0  22.0  19.0   20.5  12.0
25    Victor Oladipo  17.0   44.0   5.0   8.0   9.0   14.3   7.0

In [11]:
player_stats[player_stats['game_id'] == 131410290001]

,game_id,player,team,MP,FG,FGA,FGp,3P,3PA,3Pp,FT,FTA,FTp,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,PM,TSp,eFGp,3PAr,FTr,ORBp,DRBp,TRBp,ASTp,STLp,BLKp,TOVp,USGp,ORtg,DRtg,BPM,PIE
0,131410290001,Arron Afflalo,ORL,32:59,3.0,14.0,0.214,1.0,5.0,0.200,2.0,3.0,0.667,1.0,2.0,3.0,1.0,0.0,0.0,1.0,1.0,9.0,-14.0,0.294,0.250,0.357,0.214,3.1,8.1,5.3,4.6,0.0,0.0,6.1,20.8,69.0,111.0,-9.9,-1.1
1,131410290001,Nikola Vučević,ORL,30:39,4.0,11.0,0.364,0.0,0.0,NaN,0.0,0.0,NaN,5.0,5.0,10.0,3.0,2.0,1.0,5.0,4.0,8.0,-22.0,0.364,0.364,0.000,0.000,16.7,21.8,18.9,15.8,3.3,2.9,31.3,21.9,70.0,98.0,-5.4,3.8
2,131410290001,Jameer Nelson,ORL,30:34,4.0,13.0,0.308,3.0,7.0,0.429,1.0,1.0,1.000,1.0,4.0,5.0,7.0,2.0,0.0,2.0,1.0,12.0,-11.0,0.446,0.423,0.538,0.077,3.3,17.4,9.5,37.0,3.3,0.0,13.0,21.2,102.0,101.0,5.9,10.3
3,131410290001,Jason Maxiell,ORL,26:19,0.0,5.0,0.000,0.0,0.0,NaN,0.0,0.0,NaN,1.0,4.0,5.0,0.0,1.0,2.0,2.0,2.0,0.0,-15.0,0.000,0.000,0.000,0.000,3.9,20.3,11.0,0.0,1.9,6.8,28.6,11.2,8.0,99.0,-10.6,-1.9
4,131410290001,Maurice Harkless,ORL,23:30,6.0,13.0,0.462,2.0,2.0,1.000,0.0,1.0,0.000,1.0,0.0,1.0,0.0,1.0,0.0,0.0,4.0,14.0,-3.0,0.521,0.538,0.154,0.077,4.3,0.0,2.5,0.0,2.2,0.0,0.0,24.0,111.0,107.0,2.4,2.7
5,131410290001,E'Twaun Moore,ORL,25:45,3.0,6.0,0.500,0.0,1.0,0.000,0.0,0.0,NaN,1.0,0.0,1.0,1.0,2.0,0.0,2.0,2.0,6.0,3.0,0.500,0.500,0.167,0.000,4.0,0.0,2.2,6.1,3.9,0.0,25.0,13.0,83.0,104.0,-3.1,1.9
6,131410290001,Victor Oladipo,ORL,22:35,4.0,11.0,0.364,1.0,2.0,0.500,3.0,5.0,0.600,1.0,2.0,3.0,2.0,1.0,0.0,3.0,2.0,12.0,-11.0,0.455,0.409,0.182,0.455,4.5,11.8,7.7,15.5,2.2,0.0,18.5,30.1,85.0,104.0,-2.3,2.7
7,131410290001,Andrew Nicholson,ORL,19:17,8.0,10.0,0.800,2.0,2.0,1.000,0.0,0.0,NaN,1.0,3.0,4.0,0.0,1.0,0.0,1.0,4.0,18.0,0.0,0.900,0.900,0.200,0.000,5.3,20.7,12.0,0.0,2.6,0.0,9.1,23.9,151.0,101.0,17.3,11.8
8,131410290001,Kyle O'Quinn,ORL,14:23,3.0,7.0,0.429,0.0,0.0,NaN,0.0,0.0,NaN,0.0,4.0,4.0,0.0,0.0,3.0,1.0,2.0,6.0,10.0,0.429,0.429,0.000,0.000,0.0,37.1,16.1,0.0,0.0,18.5,12.5,23.3,78.0,92.0,-0.6,3.4
9,131410290001,Ronnie Price,ORL,8:37,1.0,2.0,0.500,0.0,0.0,NaN,0.0,0.0,NaN,0.0,1.0,1.0,3.0,0.0,0.0,0.0,2.0,2.0,6.0,0.500,0.500,0.000,0.000,0.0,15.5,6.7,54.9,0.0,0.0,0.0,9.7,144.0,108.0,1.3,2.3
10,131410290001,Solomon Jones,ORL,5:22,0.0,1.0,0.000,0.0,0.0,NaN,0.0,0.0,NaN,1.0,1.0,2.0,0.0,0.0,0.0,0.0,2.0,0.0,7.0,0.000,0.000,0.000,0.000,19.0,24.8,21.6,0.0,0.0,0.0,0.0,7.8,49.0,105.0,-14.9,-1.1
11,131410290001,Tobias Harris,ORL,Not With Team,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,131410290001,Doron Lamb,ORL,Did Not Dress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,131410290001,Paul George,IND,36:05,8.0,16.0,0.500,3.0,6.0,0.500,5.0,7.0,0.714,1.0,5.0,6.0,5.0,1.0,3.0,4.0,0.0,24.0,11.0,0.629,0.594,0.375,0.438,3.7,14.2,9.6,28.5,1.4,5.4,17.3,29.2,116.0,91.0,10.1,17.5
14,131410290001,Lance Stephenson,IND,35:38,8.0,12.0,0.667,2.0,3.0,0.667,1.0,2.0,0.500,2.0,5.0,7.0,5.0,0.0,1.0,1.0,2.0,19.0,11.0,0.738,0.750,0.250,0.167,7.5,14.3,11.4,29.0,0.0,1.8,7.2,17.8,150.0,96.0,9.2,17.1
15,131410290001,David West,IND,30:43,4.0,11.0,0.364,0.0,0.0,NaN,5.0,5.0,1.000,0.0,5.0,5.0,3.0,2.0,5.0,5.0,2.0,13.0,11.0,0.492,0.364,0.000,0.455,0.0,16.6,9.4,16.9,3.3,10.6,27.5,27.1,83.0,82.0,2.3,8.7
16,131410290001,George Hill,IND,29:04,2.0,8.0,0.250,0.0,2.0,0.000,3.0,4.0,0.750,0.0,2.0,2.0,0.0,0.0,0.0,1.0,0.0,7.0,5.0,0.359,0.250,0.250,0.500,0.0,7.0,4.0,0.0,0.0,0.0,9.3,16.9,74.0,101.0,-11.6,0.8
17,131410290001,Roy Hibbert,IND,26:54,3.0,6.0,0.500,0.0,0.0,NaN,2.0,4.0,0.500,6.0,10.0,16.0,0.0,1.0,7.0,3.0,0.0,8.0,15.0,0.515,0.500,0.000,0.667,29.7,38.0,34.4,0.0,1.9,16.9,27.9,18.3,97.0,72.0,6.7,13.3
18,131410290001,Luis Scola,IND,20:43,4.0,7.0,0.571,0.0,0.0,NaN,0.0,0.0,NaN,0.0,1.0,1.0,1.0,0.0,0.0,1.0,2.0,8.0,-2.0,0.571,0.571,0.000,0.000,0.0,4.9,2.8,9.4,0.0,0.0,12.5,17.6,105.0,101.0,-4.8,3.0
19,131410290001,C.J. Watson,IND,19:54,2.0,5.0,0.400,1.0,4.0,0.250,0.0,2.0,0.000,0.0,2.0,2.0,3.0,0.0,0.0,1.0,0.0,5.0,2.0,0.425,0.500,0.800,0.400,0.0,10.3,5.8,24.8,0.0,0.0,14.5,15.8,92.0,100.0,-4.6,3.0
20,131410290001,Ian Mahinmi,IND,16:42,0.0,1.0,0.000,0.0,0.0,NaN,4.0,6.0,0.667,1.0,2.0,3.0,0.0,0.0,2.0,2.0,5.0,4.0,-1.0,0.549,0.000,0.000,6.000,8.0,12.2,10.4,0.0,0.0,7.8,35.5,15.4,83.0,92.0,-8.6,-1.9
21,131410290001,Orlando Johnson,IND,15:12,3.0,4.0,0.750,1.0,2.0,0.500,2.0,2.0,1.000,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,9.0,11.0,0.922,0.875,0.500,0.500,0.0,6.7,3.8,0.0,0.0,0.0,17.0,17.7,147.0,101.0,4.1,5.3
22,131410290001,Solomon Hill,IND,8:07,0.0,1.0,0.000,0.0,0.0,NaN,0.0,0.0,NaN,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,-10.0,0.000,0.000,0.000,0.000,0.0,12.6,7.1,0.0,0.0,0.0,50.0,11.3,0.0,98.0,-17.9,-1.5
23,131410290001,Rasual Butler,IND,0:58,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-3.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,104.0,-6.3,0.0
24,131410290001,Chris Copeland,IND,Did Not Play,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,131410290001,Donald Sloan,IND,Did Not Play,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
ss

                 player    FG    FGA    FT   FTA    P3   ORBp   TOV
0          Anthony Lamb  16.0   40.0  13.0  15.0   7.0   61.2   7.0
1           Cam Reddish  11.0   27.0   7.0   7.0   1.0    9.9   4.0
2      Donte DiVincenzo  32.0   66.0  10.0  14.0  16.0   67.4  23.0
3        Draymond Green  40.0   73.0   9.0  12.0   3.0   39.7  39.0
4          Drew Eubanks  40.0   79.0  15.0  22.0   4.0   92.3  13.0
5        Gary Payton II  20.0   32.0   4.0   5.0   5.0   84.5   6.0
6        JaMychal Green  11.0   18.0   3.0   3.0   2.0   87.1   0.0
7         Jabari Walker  33.0   85.0  10.0  12.0   9.0   65.8   8.0
8    Jeenathan Williams  17.0   27.0   0.0   1.0   2.0   41.2   3.0
9           John Butler  15.0   43.0   3.0   4.0   7.0    8.8   1.0
10     Jonathan Kuminga  51.0   83.0  20.0  32.0  13.0   70.7   7.0
11         Jordan Poole  61.0  142.0  58.0  66.0  25.0    9.2  21.0
12        Justin Minaya   6.0   15.0   0.0   0.0   3.0   15.0   3.0
13           Kevin Knox  55.0  121.0  15.0  21.0  17.0   41.4  18.0
14         Kevon Looney  24.0   47.0  19.0  27.0   0.0  199.6   7.0
15        Klay Thompson  76.0  176.0  10.0  11.0  43.0    2.4  19.0
16      Lester Quinones   0.0    3.0   1.0   2.0   0.0    0.0   4.0
17          Moses Moody  15.0   21.0   0.0   1.0   6.0   51.4   3.0
18  Patrick Baldwin Jr.   0.0    3.0   0.0   0.0   0.0    0.0   1.0
19       Shaedon Sharpe  79.0  169.0  32.0  42.0  29.0   27.8  25.0
20          Skylar Mays  27.0   51.0   7.0   8.0  10.0    6.3   8.0
21        Stephen Curry  94.0  210.0  37.0  41.0  42.0   27.4  26.0
22      Trendon Watford  43.0   74.0  16.0  21.0   3.0   14.8   8.0

In [15]:
test = player_stats[player_stats['player'] == 'Anthony Lamb'].tail(11)
test

,game_id,player,team,MP,FG,FGA,FGp,3P,3PA,3Pp,FT,FTA,FTp,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,PM,TSp,eFGp,3PAr,FTr,ORBp,DRBp,TRBp,ASTp,STLp,BLKp,TOVp,USGp,ORtg,DRtg,BPM,PIE
301316,222303181060,Anthony Lamb,GSW,18:01,1.0,5.0,0.200,0.0,3.0,0.00,7.0,8.0,0.875,0.0,4.0,4.0,0.0,0.0,1.0,0.0,2.0,9.0,9.0,0.528,0.200,0.600,1.600,0.0,28.0,13.2,0.0,0.0,4.7,0.0,19.1,129.0,136.0,-5.0,2.9
301678,222303201074,Anthony Lamb,GSW,17:01,3.0,4.0,0.750,3.0,4.0,0.75,0.0,0.0,NaN,1.0,2.0,3.0,0.0,1.0,1.0,1.0,1.0,9.0,8.0,1.125,1.125,1.000,0.000,6.4,12.5,9.5,0.0,2.8,4.9,20.0,12.3,149.0,107.0,9.4,4.8
301940,222303221084,Anthony Lamb,GSW,21:27,3.0,7.0,0.429,2.0,5.0,0.40,1.0,1.0,1.000,1.0,7.0,8.0,1.0,0.0,0.0,1.0,2.0,9.0,-9.0,0.605,0.571,0.714,0.143,6.6,38.2,23.9,5.2,0.0,0.0,11.8,17.0,121.0,127.0,-4.3,4.4
302441,222303241103,Anthony Lamb,GSW,11:34,1.0,4.0,0.250,0.0,2.0,0.00,0.0,0.0,NaN,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,2.0,-4.0,0.250,0.250,0.500,0.000,0.0,9.7,4.8,0.0,0.0,0.0,0.0,15.2,54.0,117.0,-14.7,-0.5
302909,222303261121,Anthony Lamb,GSW,17:55,1.0,3.0,0.333,1.0,2.0,0.50,0.0,0.0,NaN,2.0,1.0,3.0,1.0,0.0,0.0,0.0,0.0,3.0,-5.0,0.500,0.500,0.667,0.000,11.6,6.7,9.3,8.6,0.0,0.0,0.0,7.6,131.0,111.0,-0.1,2.4
303269,222303281135,Anthony Lamb,GSW,17:28,1.0,2.0,0.500,1.0,2.0,0.50,1.0,2.0,0.500,0.0,0.0,0.0,2.0,1.0,0.0,2.0,2.0,4.0,8.0,0.694,0.750,1.000,1.000,0.0,0.0,0.0,13.7,2.8,0.0,41.0,12.2,93.0,115.0,-4.1,0.5
303866,222303311158,Anthony Lamb,GSW,22:47,1.0,5.0,0.200,0.0,2.0,0.00,0.0,0.0,NaN,2.0,4.0,6.0,1.0,0.0,1.0,0.0,1.0,2.0,17.0,0.200,0.200,0.400,0.000,9.2,18.7,13.9,4.7,0.0,4.0,0.0,9.1,88.0,117.0,-10.2,1.5
304308,222304021175,Anthony Lamb,GSW,15:10,2.0,4.0,0.500,0.0,2.0,0.00,4.0,4.0,1.000,3.0,5.0,8.0,0.0,1.0,1.0,2.0,1.0,8.0,-2.0,0.694,0.500,0.500,1.000,18.3,30.4,24.3,0.0,3.2,4.7,25.8,19.3,120.0,101.0,5.3,5.6
304640,222304041187,Anthony Lamb,GSW,12:02,2.0,5.0,0.400,0.0,1.0,0.00,0.0,0.0,NaN,1.0,2.0,3.0,0.0,0.0,0.0,0.0,2.0,4.0,-11.0,0.400,0.400,0.200,0.000,9.1,16.6,13.0,0.0,0.0,0.0,0.0,16.5,110.0,127.0,-12.9,0.7
305242,222304071211,Anthony Lamb,GSW,4:22,1.0,1.0,1.000,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,-2.0,1.000,1.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,0.0,50.0,19.5,64.0,110.0,-12.6,0.0
305719,222304091230,Anthony Lamb,GSW,10:41,2.0,2.0,1.000,0.0,0.0,NaN,0.0,0.0,NaN,0.0,3.0,3.0,3.0,0.0,1.0,0.0,2.0,4.0,11.0,1.197,1.500,1.000,2.000,13.6,0.0,5.1,9.2,4.1,0.0,21.0,18.1,169.0,94.0,14.1,3.1

In [18]:
test[0:10].sum()

game_id                                        2223034831308
player     Anthony LambAnthony LambAnthony LambAnthony La...
team                          GSWGSWGSWGSWGSWGSWGSWGSWGSWGSW
MP         18:0117:0121:2711:3417:5517:2822:4715:1012:024:22
FG                                                      16.0
FGA                                                     40.0
FGp                                                    4.562
3P                                                       7.0
3PA                                                     23.0
3Pp                                                     2.15
FT                                                      13.0
FTA                                                     15.0
FTp                                                    3.375
ORB                                                     10.0
DRB                                                     26.0
TRB                                                     36.0
AST                                                      5.0
STL                                                      3.0
BLK                                                      4.0
TOV                                                      7.0
PF                                                      13.0
PTS                                                     52.0
PM                                                       9.0
TSp                                                    5.996
eFGp                                                   5.496
3PAr                                                   5.581
FTr                                                    3.743
ORBp                                                    61.2
DRBp                                                   160.8
TRBp                                                   111.9
ASTp                                                    32.2
STLp                                                     8.8
BLKp                                                    18.3
TOVp                                                   148.6
USGp                                                   147.8
ORtg                                                  1059.0
DRtg                                                  1168.0
BPM                                                    -49.2
PIE                                                     22.3
dtype: object

In [32]:
head_test = player_stats[player_stats['player'] == 'Arron Afflalo'].head(11)
# head_test
head_test[0:10].sum()

game_id                                        1314109260647
player     Arron AfflaloArron AfflaloArron AfflaloArron A...
team                          ORLORLORLORLORLORLORLORLORLORL
MP         32:5941:0435:2137:2335:3334:0336:3338:3940:083...
FG                                                      73.0
FGA                                                    150.0
FGp                                                    4.864
3P                                                      26.0
3PA                                                     52.0
3Pp                                                    4.227
FT                                                      45.0
FTA                                                     56.0
FTp                                                    7.436
ORB                                                      2.0
DRB                                                     48.0
TRB                                                     50.0
AST                                                     48.0
STL                                                      9.0
BLK                                                      0.0
TOV                                                     25.0
PF                                                      17.0
PTS                                                    217.0
PM                                                      11.0
TSp                                                    6.166
eFGp                                                   5.729
3PAr                                                   3.511
FTr                                                    4.012
ORBp                                                     5.8
DRBp                                                   135.2
TRBp                                                    72.4
ASTp                                                   212.7
STLp                                                    11.9
BLKp                                                     0.0
TOVp                                                   121.8
USGp                                                   238.7
ORtg                                                  1163.0
DRtg                                                  1055.0
BPM                                                     40.8
PIE                                                    115.5
dtype: object

In [30]:
game_id = 131411200164
query = f'''select player, SUM(FG) as FG, SUM(FGA) as FGA, SUM(FT) as FT, SUM(FTA) as FTA, SUM("3P") as P3, SUM(ORBp) as ORBp, SUM(TOV) as TOV
from ( select ROW_NUMBER() OVER (PARTITION BY d.player order by d.date desc ) r, d.*  
    from ( select game_id, player from player_stats ps where ps.game_id={game_id} ) gs
    inner join ( select b.date,  a.* from player_stats a inner join game_info b on a.game_id = b.game_id ) d
        on gs.player=d.player
) k
where (k.r BETWEEN 2 and 11)
group by player;'''

fff = pd.read_sql(query, con=conn)

In [42]:
game_id = 131410290001
query = f'''select player, SUM(FG)
from ( select ROW_NUMBER() OVER (PARTITION BY d.player order by d.date desc ) r, d.*  
    from ( select game_id, player from player_stats ps where ps.game_id={game_id} ) gs
    inner join ( select b.date,  a.* from player_stats a inner join game_info b on a.game_id = b.game_id ) d
        on gs.player=d.player
) k
where (k.r BETWEEN 2 and 11)
group by player;'''

fff = pd.read_sql(query, con=conn)

In [43]:
fff

              player  SUM(FG)
0   Andrew Nicholson      4.0
1      Arron Afflalo      3.0
2        C.J. Watson      8.0
3     Chris Copeland      1.0
4         David West     26.0
5       Donald Sloan     23.0
6         Doron Lamb     17.0
7      E'Twaun Moore     12.0
8        George Hill      3.0
9        Ian Mahinmi      NaN
10     Jameer Nelson      0.0
11     Jason Maxiell     20.0
12      Kyle O'Quinn      4.0
13  Lance Stephenson     34.0
14        Luis Scola      0.0
15  Maurice Harkless      0.0
16    Nikola Vučević     76.0
17   Orlando Johnson      9.0
18       Paul George     85.0
19     Rasual Butler     13.0
20      Ronnie Price      1.0
21       Roy Hibbert      0.0
22      Solomon Hill      1.0
23     Solomon Jones      0.0
24     Tobias Harris     57.0
25    Victor Oladipo     17.0

In [35]:
player_stats[player_stats['game_id'] == 131411200164]

,game_id,player,team,MP,FG,FGA,FGp,3P,3PA,3Pp,FT,FTA,FTp,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,PM,TSp,eFGp,3PAr,FTr,ORBp,DRBp,TRBp,ASTp,STLp,BLKp,TOVp,USGp,ORtg,DRtg,BPM,PIE
4199,131411200164,LeBron James,MIA,29:05,5.0,11.0,0.455,0.0,2.0,0.000,11.0,11.0,1.000,1.0,5.0,6.0,7.0,1.0,1.0,4.0,0.0,21.0,23.0,0.663,0.455,0.182,1.000,5.5,23.6,15.2,38.8,1.8,3.9,20.2,30.0,135.0,98.0,6.9,14.0
4200,131411200164,Mario Chalmers,MIA,27:53,3.0,5.0,0.600,1.0,1.0,1.000,2.0,2.0,1.000,1.0,2.0,3.0,8.0,2.0,0.0,2.0,4.0,9.0,19.0,0.765,0.700,0.200,0.400,5.7,9.8,7.9,41.9,3.7,0.0,25.4,12.4,153.0,100.0,6.4,7.6
4201,131411200164,Shane Battier,MIA,25:00,2.0,3.0,0.667,2.0,3.0,0.667,0.0,0.0,NaN,0.0,4.0,4.0,2.0,0.0,1.0,0.0,0.0,6.0,18.0,1.000,1.000,1.000,0.000,0.0,21.9,11.8,11.2,0.0,4.6,0.0,5.3,211.0,103.0,8.1,6.5
4202,131411200164,Chris Bosh,MIA,23:59,7.0,10.0,0.700,1.0,2.0,0.500,3.0,4.0,0.750,2.0,3.0,5.0,0.0,2.0,1.0,2.0,2.0,18.0,27.0,0.765,0.750,0.200,0.400,13.3,17.2,15.4,0.0,4.3,4.8,14.5,25.2,132.0,93.0,5.4,9.3
4203,131411200164,James Jones,MIA,20:00,5.0,8.0,0.625,5.0,7.0,0.714,2.0,3.0,0.667,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,17.0,20.0,0.912,0.938,0.875,0.375,0.0,6.9,3.7,9.2,2.6,0.0,9.7,22.7,157.0,103.0,15.7,8.4
4204,131411200164,Rashard Lewis,MIA,24:51,1.0,4.0,0.250,0.0,1.0,0.000,0.0,0.0,NaN,2.0,0.0,2.0,3.0,2.0,0.0,2.0,1.0,2.0,15.0,0.250,0.250,0.250,0.000,12.9,0.0,5.9,16.1,4.1,0.0,33.3,10.6,86.0,101.0,-3.2,1.1
4205,131411200164,Michael Beasley,MIA,20:37,4.0,10.0,0.400,0.0,0.0,NaN,6.0,6.0,1.000,1.0,6.0,7.0,0.0,0.0,1.0,2.0,4.0,14.0,9.0,0.554,0.400,0.000,0.600,7.8,39.9,25.1,0.0,0.0,5.5,13.7,31.2,113.0,98.0,-10.8,5.1
4206,131411200164,Norris Cole,MIA,20:07,3.0,6.0,0.500,3.0,3.0,1.000,0.0,0.0,NaN,0.0,4.0,4.0,5.0,1.0,0.0,3.0,1.0,9.0,9.0,0.750,0.750,0.500,0.000,0.0,27.3,14.7,38.7,2.6,0.0,33.3,19.7,119.0,98.0,5.8,6.7
4207,131411200164,Ray Allen,MIA,19:59,2.0,8.0,0.250,2.0,3.0,0.667,0.0,0.0,NaN,1.0,1.0,2.0,0.0,1.0,0.0,3.0,0.0,6.0,3.0,0.375,0.375,0.375,0.000,8.0,6.9,7.4,0.0,2.6,0.0,27.3,24.2,65.0,103.0,-14.2,-0.3
4208,131411200164,Chris Andersen,MIA,17:43,4.0,6.0,0.667,0.0,0.0,NaN,2.0,2.0,1.000,4.0,1.0,5.0,0.0,1.0,2.0,2.0,2.0,10.0,1.0,0.727,0.667,0.000,0.333,36.1,7.7,20.8,0.0,2.9,12.9,22.5,22.1,127.0,94.0,1.1,5.1
4209,131411200164,Udonis Haslem,MIA,5:55,1.0,1.0,1.000,0.0,0.0,NaN,3.0,4.0,0.750,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,5.0,0.0,0.906,1.000,0.000,4.000,0.0,23.2,12.5,0.0,8.7,0.0,0.0,20.5,190.0,84.0,14.7,2.8
4210,131411200164,Roger Mason,MIA,4:51,1.0,2.0,0.500,1.0,2.0,0.500,0.0,0.0,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,-4.0,0.750,0.750,1.000,0.000,0.0,0.0,0.0,35.2,0.0,0.0,0.0,18.1,180.0,111.0,12.0,1.7
4211,131411200164,Joel Anthony,MIA,Did Not Play,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4212,131411200164,Victor Oladipo,ORL,35:36,5.0,12.0,0.417,2.0,5.0,0.400,8.0,8.0,1.000,0.0,4.0,4.0,2.0,5.0,2.0,8.0,1.0,20.0,-19.0,0.644,0.500,0.417,0.667,0.0,18.0,8.3,12.1,7.2,5.4,34.0,30.4,87.0,115.0,0.9,9.0
4213,131411200164,Arron Afflalo,ORL,34:55,9.0,16.0,0.563,7.0,9.0,0.778,5.0,5.0,1.000,0.0,2.0,2.0,2.0,0.0,1.0,3.0,2.0,30.0,-28.0,0.824,0.781,0.563,0.313,0.0,9.2,4.2,16.5,0.0,2.7,14.2,28.0,134.0,136.0,8.9,12.6
4214,131411200164,Jameer Nelson,ORL,34:53,5.0,13.0,0.385,4.0,9.0,0.444,3.0,4.0,0.750,2.0,3.0,5.0,5.0,0.0,0.0,5.0,2.0,17.0,-25.0,0.576,0.538,0.692,0.308,7.9,13.8,10.6,31.1,0.0,0.0,25.3,26.1,99.0,136.0,-6.5,5.6
4215,131411200164,Maurice Harkless,ORL,30:36,2.0,7.0,0.286,0.0,2.0,0.000,1.0,2.0,0.500,1.0,1.0,2.0,3.0,4.0,0.0,2.0,3.0,5.0,-25.0,0.317,0.286,0.286,0.286,4.5,5.2,4.8,18.2,6.7,0.0,20.2,14.9,74.0,123.0,-5.2,1.4
4216,131411200164,Nikola Vučević,ORL,22:33,2.0,7.0,0.286,0.0,0.0,NaN,2.0,2.0,1.000,3.0,3.0,6.0,1.0,0.0,0.0,1.0,6.0,6.0,-18.0,0.381,0.286,0.000,0.286,18.2,21.3,19.6,8.6,0.0,0.0,11.3,18.1,93.0,134.0,-15.3,-0.3
4217,131411200164,Jason Maxiell,ORL,20:54,2.0,6.0,0.333,0.0,0.0,NaN,0.0,0.0,NaN,0.0,2.0,2.0,0.0,0.0,1.0,0.0,2.0,4.0,-3.0,0.333,0.333,0.000,0.000,0.0,15.3,7.1,0.0,0.0,4.6,0.0,13.2,69.0,134.0,-11.5,0.3
4218,131411200164,Solomon Jones,ORL,16:57,1.0,4.0,0.250,0.0,0.0,NaN,0.0,0.0,NaN,1.0,2.0,3.0,1.0,2.0,1.0,1.0,2.0,2.0,-16.0,0.250,0.250,0.000,0.000,8.1,18.9,13.1,10.8,6.1,5.7,20.0,13.6,64.0,118.0,-4.7,1.1
4219,131411200164,E'Twaun Moore,ORL,16:19,1.0,3.0,0.333,0.0,1.0,0.000,0.0,0.0,NaN,0.0,1.0,1.0,3.0,1.0,0.0,2.0,1.0,2.0,-2.0,0.333,0.333,0.333,0.000,0.0,9.8,4.5,33.9,3.1,0.0,40.0,14.1,70.0,130.0,-8.7,1.1
4220,131411200164,Doron Lamb,ORL,15:27,1.0,2.0,0.500,1.0,2.0,0.500,0.0,0.0,NaN,0.0,0.0,0.0,1.0,0.0,0.0,2.0,1.0,3.0,-4.0,0.750,0.750,1.000,0.000,0.0,0.0,0.0,12.0,0.0,0.0,50.0,11.9,74.0,140.0,-10.6,0.0
4221,131411200164,Ronnie Price,ORL,5:55,1.0,1.0,1.000,1.0,1.0,1.000,0.0,0.0,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,3.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,28.0,0.0,0.0,NaN,0.0,252.0,140.0,-3.3,1.1
4222,131411200164,Andrew Nicholson,ORL,5:55,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.500,1.500,1.000,0.000,0.0,0.0,0.0,0.0,8.7,0.0,0.0,7.8,300.0,119.0,13.4,0.0
4223,131411200164,Tobias Harris,ORL,Did Not Dress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4224,131411200164,Kyle O'Quinn,ORL,Did Not Dress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
id_ref = player_stats[['player', 'team', 'game_id']]
id_ref

                  player team       game_id
0          Arron Afflalo  ORL  131410290001
1         Nikola Vučević  ORL  131410290001
2          Jameer Nelson  ORL  131410290001
3          Jason Maxiell  ORL  131410290001
4       Maurice Harkless  ORL  131410290001
...                  ...  ...           ...
305727       John Butler  POR  222304091230
305728   Chance Comanche  POR  222304091230
305729     Jabari Walker  POR  222304091230
305730      Drew Eubanks  POR  222304091230
305731       Cam Reddish  POR  222304091230

[305732 rows x 3 columns]

In [8]:
mm = pd.merge(ss, id_ref[['player', 'team']][id_ref['game_id'] == game_id], on=['player'])
mm

,player,SUM(FG),SUM(FGA),SUM(FT),SUM(FTA),"SUM(""3P"")",SUM(ORBp),SUM(TOV),team
0,Anthony Lamb,16.0,40.0,13.0,15.0,7.0,61.2,7.0,GSW
1,Cam Reddish,11.0,27.0,7.0,7.0,1.0,9.9,4.0,POR
2,Donte DiVincenzo,32.0,66.0,10.0,14.0,16.0,67.4,23.0,GSW
3,Draymond Green,40.0,73.0,9.0,12.0,3.0,39.7,39.0,GSW
4,Drew Eubanks,40.0,79.0,15.0,22.0,4.0,92.3,13.0,POR
5,Gary Payton II,20.0,32.0,4.0,5.0,5.0,84.5,6.0,GSW
6,JaMychal Green,11.0,18.0,3.0,3.0,2.0,87.1,0.0,GSW
7,Jabari Walker,33.0,85.0,10.0,12.0,9.0,65.8,8.0,POR
8,Jeenathan Williams,17.0,27.0,0.0,1.0,2.0,41.2,3.0,POR
9,John Butler,15.0,43.0,3.0,4.0,7.0,8.8,1.0,POR
10,Jonathan Kuminga,51.0,83.0,20.0,32.0,13.0,70.7,7.0,GSW
11,Jordan Poole,61.0,142.0,58.0,66.0,25.0,9.2,21.0,GSW
12,Justin Minaya,6.0,15.0,0.0,0.0,3.0,15.0,3.0,POR
13,Kevin Knox,55.0,121.0,15.0,21.0,17.0,41.4,18.0,POR
14,Kevon Looney,24.0,47.0,19.0,27.0,0.0,199.6,7.0,GSW
15,Klay Thompson,76.0,176.0,10.0,11.0,43.0,2.4,19.0,GSW
16,Lester Quinones,0.0,3.0,1.0,2.0,0.0,0.0,4.0,GSW
17,Moses Moody,15.0,21.0,0.0,1.0,6.0,51.4,3.0,GSW
18,Patrick Baldwin Jr.,0.0,3.0,0.0,0.0,0.0,0.0,1.0,GSW
19,Shaedon Sharpe,79.0,169.0,32.0,42.0,29.0,27.8,25.0,POR
20,Skylar Mays,27.0,51.0,7.0,8.0,10.0,6.3,8.0,POR
21,Stephen Curry,94.0,210.0,37.0,41.0,42.0,27.4,26.0,GSW
22,Trendon Watford,43.0,74.0,16.0,21.0,3.0,14.8,8.0,POR

In [10]:
nn = mm.groupby('team').sum()/10
nn

      SUM(FG)  SUM(FGA)  SUM(FT)  SUM(FTA)  SUM("3P")  SUM(ORBp)  SUM(TOV)
team
GSW      44.0      91.4     18.4      22.9       16.2      70.06      16.3
POR      32.6      69.1     10.5      13.8        8.5      32.33       9.1

In [20]:
away_team = game_info['away_team'][game_info['game_id'] == game_id]

11978    GSW
Name: away_team, dtype: object

In [38]:
# nn.loc[away_team]['SUM(FG)'] + (0.5*SUM("3P"))
nn.loc[away_team]['SUM("3P")']

team
GSW    16.2
Name: SUM("3P"), dtype: float64

In [34]:
four_factor_columns = ['game_id', 'a_eFGp', 'a_FTr', 'a_ORBp', 'a_TOVp', 'h_eFGp', 'h_FTr', 'h_ORBp', 'h_TOVp']
four_factor_stats = pd.DataFrame(columns=four_factor_columns)
# four_factor_stats['game_id'] = game_id
# four_factor_stats
    gid = game_id
    eFGp = ( nn.loc[team]['SUM(FG)'] + (0.5*nn.loc[team]['"3P"']) ) / nn.loc[team]['SUM(FGA)']
    FTr = nn.loc[team]['SUM(FT)'] / nn.loc[team]['SUM(FGA)']
    ORBp = nn.loc[team]['SUM(ORBp)']*0.01
    TOVp = nn.loc[team]['SUM(TOV)'] / ( nn.loc[team]['SUM(FGA)'] + 0.44*nn.loc[team]['SUM(FTA)'] + nn.loc[team]['SUM(TOV)'] )
    
    eFGp = (stat_df['FG'].mean() + (0.5 * stat_df['3P'].mean())) / stat_df['FGA'].mean()
    FTr = stat_df['FT'].mean() / stat_df['FGA'].mean()
    ORBp = stat_df['ORBp'].mean()*0.01
    TOVp = stat_df['TOV'].mean() / (stat_df['FGA'].mean() + (0.44*stat_df['FTA'].mean()) + stat_df['TOV'].mean())

Empty DataFrame
Columns: [a_eFGp, a_FTr, a_ORBp, a_TOVp, h_eFGp, h_FTr, h_ORBp, h_TOVp]
Index: []

In [8]:
list(game_info['game_id'][0:50])

[131410290001,
 131410290002,
 131410290003,
 131410300004,
 131410300005,
 131410300006,
 131410300007,
 131410300008,
 131410300009,
 131410300010,
 131410300011,
 131410300012,
 131410300013,
 131410300014,
 131410300015,
 131410300016,
 131410300017,
 131410310018,
 131410310019,
 131411010020,
 131411010021,
 131411010022,
 131411010023,
 131411010024,
 131411010025,
 131411010026,
 131411010027,
 131411010028,
 131411010029,
 131411010030,
 131411010031,
 131411010032,
 131411020033,
 131411020034,
 131411020035,
 131411020036,
 131411020037,
 131411020038,
 131411020039,
 131411020040,
 131411030041,
 131411030042,
 131411030043,
 131411030044,
 131411030045,
 131411030046,
 131411040047,
 131411040048,
 131411040049,
 131411040050]

In [5]:
game_ids = list(game_info['game_id'][0:10])

id_ref = player_stats[['player', 'team', 'game_id']]

four_factor_columns = ['game_id', 'a_eFGp', 'a_FTr', 'a_ORBp', 'a_TOVp', 'h_eFGp', 'h_FTr', 'h_ORBp', 'h_TOVp']
player_four_factor_10 = pd.DataFrame(columns=four_factor_columns)

for game_id in game_ids:
    
    away_team = game_info['away_team'][game_info['game_id'] == game_id]
    home_team = game_info['home_team'][game_info['game_id'] == game_id]

    query = f'''select player, SUM(FG) as FG, SUM(FGA) as FGA, SUM(FT) as FT, SUM(FTA) as FTA, SUM("3P") as P3, SUM(ORBp) as ORBp, SUM(TOV) as TOV
                from ( select ROW_NUMBER() OVER (PARTITION BY d.player order by d.date desc ) r, d.*  
                    from ( select game_id, player from player_stats ps where ps.game_id={game_id} ) gs
                    inner join ( select b.date,  a.* from player_stats a inner join game_info b on a.game_id = b.game_id ) d
                        on gs.player=d.player
                ) k
                where (k.r BETWEEN 2 and 11)
                group by player;'''

    stat_df = pd.read_sql(query, con=conn)
    player_agg_stats = pd.merge(stat_df, id_ref[['player', 'team']][id_ref['game_id'] == game_id], on=['player'])
    team_avg_stats = player_agg_stats.groupby('team').sum()/10
    
    a_eFGp = float( ( team_avg_stats.loc[away_team]['FG'] + (0.5*team_avg_stats.loc[away_team]['P3']) ) / team_avg_stats.loc[away_team]['FGA'] )
    a_FTr = float( team_avg_stats.loc[away_team]['FT'] / team_avg_stats.loc[away_team]['FGA'] )
    a_ORBp = float( team_avg_stats.loc[away_team]['ORBp']*0.01 )
    a_TOVp = float( team_avg_stats.loc[away_team]['TOV'] / ( team_avg_stats.loc[away_team]['FGA'] + 0.44*team_avg_stats.loc[away_team]['FTA'] + team_avg_stats.loc[away_team]['TOV'] ) )
    
    h_eFGp = float( ( team_avg_stats.loc[home_team]['FG'] + (0.5*team_avg_stats.loc[home_team]['P3']) ) / team_avg_stats.loc[home_team]['FGA'] )
    h_FTr = float( team_avg_stats.loc[home_team]['FT'] / team_avg_stats.loc[home_team]['FGA'] )
    h_ORBp = float( team_avg_stats.loc[home_team]['ORBp']*0.01 )
    h_TOVp = float( team_avg_stats.loc[home_team]['TOV'] / ( team_avg_stats.loc[home_team]['FGA'] + 0.44*team_avg_stats.loc[home_team]['FTA'] + team_avg_stats.loc[home_team]['TOV'] ) )

    stats = [game_id, a_eFGp, a_FTr, a_ORBp, a_TOVp, h_eFGp, h_FTr, h_ORBp, h_TOVp]
    idx = player_four_factor_10.shape[0]
    player_four_factor_10.loc[idx] = stats

In [6]:
player_four_factor_10

,game_id,a_eFGp,a_FTr,a_ORBp,a_TOVp,h_eFGp,h_FTr,h_ORBp,h_TOVp
0,1.314103e+11,0.578883,0.150485,0.3131,0.120344,0.469854,0.249480,0.2096,0.120013
1,1.314103e+11,0.515439,0.339667,0.3663,0.110976,0.496129,0.216774,0.4573,0.122870
2,1.314103e+11,0.555740,0.159734,0.3481,0.128109,0.460474,0.166008,0.2461,0.141207
3,1.314103e+11,0.580285,0.150407,0.4274,0.157888,0.469646,0.232715,0.7572,0.095816
4,1.314103e+11,0.520501,0.257403,0.4421,0.156555,0.502846,0.189753,0.3798,0.113720
5,1.314103e+11,0.492868,0.215531,0.4036,0.123493,0.402724,0.237354,0.5130,0.172683
6,1.314103e+11,0.498291,0.186325,0.6161,0.140997,0.457576,0.163636,0.4507,0.119789
7,1.314103e+11,0.546266,0.212662,0.4459,0.146649,0.495136,0.118677,0.2897,0.092599
8,1.314103e+11,0.469854,0.249480,0.2096,0.120013,0.534539,0.235197,0.2822,0.118532
9,1.314103e+11,0.578883,0.150485,0.3131,0.120344,0.470755,0.209434,0.3489,0.116335

In [8]:
# pd.concat([game_info, player_four_factor_10], axis=1)
game_info.merge(player_four_factor_10, on='game_id')

,game_id,season,date,away_team,away_score,home_team,home_score,result,a_eFGp,a_FTr,a_ORBp,a_TOVp,h_eFGp,h_FTr,h_ORBp,h_TOVp
0,131410290001,1314,2013-10-29,ORL,87,IND,97,1,0.578883,0.150485,0.3131,0.120344,0.469854,0.249480,0.2096,0.120013
1,131410290002,1314,2013-10-29,CHI,95,MIA,107,1,0.515439,0.339667,0.3663,0.110976,0.496129,0.216774,0.4573,0.122870
2,131410290003,1314,2013-10-29,LAC,103,LAL,116,1,0.555740,0.159734,0.3481,0.128109,0.460474,0.166008,0.2461,0.141207
3,131410300004,1314,2013-10-30,BRK,94,CLE,98,1,0.580285,0.150407,0.4274,0.157888,0.469646,0.232715,0.7572,0.095816
4,131410300005,1314,2013-10-30,BOS,87,TOR,93,1,0.520501,0.257403,0.4421,0.156555,0.502846,0.189753,0.3798,0.113720
5,131410300006,1314,2013-10-30,MIA,110,PHI,114,1,0.492868,0.215531,0.4036,0.123493,0.402724,0.237354,0.5130,0.172683
6,131410300007,1314,2013-10-30,WAS,102,DET,113,1,0.498291,0.186325,0.6161,0.140997,0.457576,0.163636,0.4507,0.119789
7,131410300008,1314,2013-10-30,MIL,83,NYK,90,1,0.546266,0.212662,0.4459,0.146649,0.495136,0.118677,0.2897,0.092599
8,131410300009,1314,2013-10-30,IND,95,NOP,90,0,0.469854,0.249480,0.2096,0.120013,0.534539,0.235197,0.2822,0.118532
9,131410300010,1314,2013-10-30,ORL,115,MIN,120,1,0.578883,0.150485,0.3131,0.120344,0.470755,0.209434,0.3489,0.116335

In [30]:
four_factor_df = game_info
# four_factor_df =

In [33]:
four_factor_df.loc[four_factor_df['game_id'] == game_id]

,game_id,season,date,away_team,away_score,home_team,home_score,result
11978,222304091230,2223,2023-04-09,GSW,157,POR,101,0

In [ ]:
# ss[ss['player'] == 'Trendon Watford']

In [ ]:
# ind_sum_df  = ss.groupby('player').sum()
# ind_sum_df

In [ ]:
# ind_sum_df.sum()

In [ ]:
# for game_id in game_ids:
#     query_df = pd.read_sql(query, con=conn)

In [ ]:
# gid = 222304091230
# away_team = 'GSW'
# date = '2023-04-09'
game_ids = list(team_stats['game_id'].unique())

In [ ]:
def create_gid_query(game_id, date, team='away'):
    away_gid_query = f'''
    SELECT gi.game_id
    FROM game_info gi
    WHERE (gi.away_team = (SELECT away_team FROM game_info WHERE game_id = '{game_id}')
            AND gi.date < '{date}')
       OR (gi.home_team = (SELECT away_team FROM game_info WHERE game_id = '{game_id}')
            AND gi.date < '{date}')
    ORDER BY gi.date DESC
    LIMIT 10;
    '''
    
    home_gid_query = f'''
    SELECT gi.game_id
    FROM game_info gi
    WHERE (gi.away_team = (SELECT home_team FROM game_info WHERE game_id = '{game_id}')
            AND gi.date < '{date}')
       OR (gi.home_team = (SELECT home_team FROM game_info WHERE game_id = '{game_id}')
            AND gi.date < '{date}')
    ORDER BY gi.date DESC
    LIMIT 10;
    '''
    
    if team == 'away':
        return away_gid_query
    elif team == 'home':
        return home_gid_query

In [ ]:
def create_4F_df(query, conn, team_stats, team='away'):
    
    gid_query_df = pd.read_sql(query, con=conn)
    stat_df = gid_query_df.merge(team_stats[['game_id', 'team', 'FG', 'FGA', 'FT', 'FTA', '3P', 'ORBp', 'TOV']])
    
    if team == 'away':
        stat_df = stat_df[stat_df['team'] == away_team].reset_index(drop=True)
    elif team =='home':
        stat_df = stat_df[stat_df['team'] == home_team].reset_index(drop=True)
    
    eFGp = (stat_df['FG'].mean() + (0.5 * stat_df['3P'].mean())) / stat_df['FGA'].mean()
    FTr = stat_df['FT'].mean() / stat_df['FGA'].mean()
    ORBp = stat_df['ORBp'].mean()*0.01
    TOVp = stat_df['TOV'].mean() / (stat_df['FGA'].mean() + (0.44*stat_df['FTA'].mean()) + stat_df['TOV'].mean())
    
    if team == 'away':
        comp_df = pd.DataFrame(data = [[eFGp, FTr, ORBp, TOVp]], columns=['a_eFGp', 'a_FTr', 'a_ORBp', 'a_TOVp'])
    elif team =='home':
        comp_df = pd.DataFrame(data = [[eFGp, FTr, ORBp, TOVp]], columns=['h_eFGp', 'h_FTr', 'h_ORBp', 'h_TOVp'])
    
    return comp_df

In [ ]:
away_stats_df = pd.DataFrame(data = [[eFGp, FTr, ORBp, TOVp]], columns=['a_eFGp', 'a_FTr', 'a_ORBp', 'a_TOVp'])
away_stats_df

In [ ]:
four_factor_columns = list(game_info.columns) + ['a_eFGp', 'a_FTr', 'a_ORBp', 'a_TOVp', 'h_eFGp', 'h_FTr', 'h_ORBp', 'h_TOVp']
four_factor_df = pd.DataFrame(columns=four_factor_columns)
four_factor_df = four_factor_df.append(stats_4F, ignore_index=True)
four_factor_df = four_factor_df.append(stats_4F, ignore_index=True)
four_factor_df

In [ ]:
for game_id in game_ids:
    
    date = game_info[game_info['game_id'] == game_id]['date'].values[0]
    away_team = game_info[game_info['game_id'] == game_id]['away_team'].values[0]
    home_team = game_info[game_info['game_id'] == game_id]['home_team'].values[0]
    
    away_gid_query = create_gid_query(game_id = game_id, date=date, team='away')
    
    away_gid_query_df = pd.read_sql(away_gid_query, con=conn)
    away_4F_df = away_gid_query_df.merge(team_stats[['game_id', 'team', 'FG', 'FGA', 'FT', 'FTA', '3P', 'ORBp', 'TOV']])
    away_4F_df = away_4F_df[away_4F_df['team'] == away_team].reset_index(drop=True)
    
    eFGp = (away_4F_df['FG'].mean() + (0.5 * away_4F_df['3P'].mean())) / away_4F_df['FGA'].mean()
    FTr = away_4F_df['FT'].mean() / away_4F_df['FGA'].mean()
    ORBp = away_4F_df['ORBp'].mean()
    TOVp = away_4F_df['TOV'].mean() / (away_4F_df['FGA'].mean() + (0.44*away_4F_df['FTA'].mean()) + away_4F_df['TOV'].mean())

In [ ]:
four_factor_columns = list(game_info.columns) + ['a_eFGp', 'a_FTr', 'a_ORBp', 'a_TOVp', 'h_eFGp', 'h_FTr', 'h_ORBp', 'h_TOVp']
four_factor_df = pd.DataFrame(columns=four_factor_columns)

for game_id in game_ids:

    date = game_info[game_info['game_id'] == game_id]['date'].values[0]
    away_team = game_info[game_info['game_id'] == game_id]['away_team'].values[0]
    home_team = game_info[game_info['game_id'] == game_id]['home_team'].values[0]

    away_gid_query = create_gid_query(game_id = game_id, date=date, team='away')
    away_stats = create_4F_df(query=away_gid_query, conn=conn, team_stats=team_stats, team='away')

    home_gid_query = create_gid_query(game_id=game_id, date=date, team='home')
    home_stats = create_4F_df(query=home_gid_query, conn=conn, team_stats=team_stats, team='home')
    
    agg_stats = pd.concat([away_stats, home_stats], axis=1)
    gid_info = game_info[game_info['game_id'] == game_id].reset_index(drop=True)
    
    stats_4F = pd.concat([gid_info, agg_stats], axis=1)
    four_factor_df = four_factor_df.append(stats_4F, ignore_index=True)

In [ ]:
four_factor_df.head(25)

In [ ]:
four_factor_df.to_csv('four_factor_10.csv')