In [1]:
import numpy as np
import pandas as pd
import sqlite3

import warnings
warnings.filterwarnings("ignore")

pd.set_option('display.max_columns', None)

In [2]:
conn = sqlite3.connect(r'C:/Users/diper/Documents/Github/NBA-Prediction-Modeling/data/NBA-Boxscore-Database.sqlite')

In [3]:
query = 'SELECT * from game_info'
game_info = pd.read_sql(query, con=conn)
# account for team name change following the 2013-2014 season
game_info['away_team'].replace('CHA', 'CHO', inplace=True)
game_info['home_team'].replace('CHA', 'CHO', inplace=True)
game_info

,game_id,season,date,away_team,away_score,home_team,home_score,result
0,131410290001,1314,2013-10-29,ORL,87,IND,97,1
1,131410290002,1314,2013-10-29,CHI,95,MIA,107,1
2,131410290003,1314,2013-10-29,LAC,103,LAL,116,1
3,131410300004,1314,2013-10-30,BRK,94,CLE,98,1
4,131410300005,1314,2013-10-30,BOS,87,TOR,93,1
...,...,...,...,...,...,...,...,...
11974,222304091226,2223,2023-04-09,UTA,117,LAL,128,1
11975,222304091227,2223,2023-04-09,NOP,108,MIN,113,1
11976,222304091228,2223,2023-04-09,MEM,100,OKC,115,1
11977,222304091229,2223,2023-04-09,LAC,119,PHO,114,0
11978,222304091230,2223,2023-04-09,GSW,157,POR,101,0

In [ ]:
query = 'SELECT * from team_stats'
team_stats = pd.read_sql(query, con=conn)
# account for team name change following the 2013-2014 season
team_stats['team'].replace('CHA', 'CHO', inplace=True)
team_stats

In [4]:
query = 'SELECT * from player_stats'
player_stats = pd.read_sql(query, con=conn)
# account for team name change following the 2013-2014 season
player_stats['team'].replace('CHA', 'CHO', inplace=True)
player_stats

,game_id,player,team,MP,FG,FGA,FGp,3P,3PA,3Pp,FT,FTA,FTp,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,PM,TSp,eFGp,3PAr,FTr,ORBp,DRBp,TRBp,ASTp,STLp,BLKp,TOVp,USGp,ORtg,DRtg,BPM,PIE
0,131410290001,Arron Afflalo,ORL,32:59,3.0,14.0,0.214,1.0,5.0,0.200,2.0,3.0,0.667,1.0,2.0,3.0,1.0,0.0,0.0,1.0,1.0,9.0,-14.0,0.294,0.250,0.357,0.214,3.1,8.1,5.3,4.6,0.0,0.0,6.1,20.8,69.0,111.0,-9.9,-1.1
1,131410290001,Nikola Vučević,ORL,30:39,4.0,11.0,0.364,0.0,0.0,NaN,0.0,0.0,NaN,5.0,5.0,10.0,3.0,2.0,1.0,5.0,4.0,8.0,-22.0,0.364,0.364,0.000,0.000,16.7,21.8,18.9,15.8,3.3,2.9,31.3,21.9,70.0,98.0,-5.4,3.8
2,131410290001,Jameer Nelson,ORL,30:34,4.0,13.0,0.308,3.0,7.0,0.429,1.0,1.0,1.000,1.0,4.0,5.0,7.0,2.0,0.0,2.0,1.0,12.0,-11.0,0.446,0.423,0.538,0.077,3.3,17.4,9.5,37.0,3.3,0.0,13.0,21.2,102.0,101.0,5.9,10.3
3,131410290001,Jason Maxiell,ORL,26:19,0.0,5.0,0.000,0.0,0.0,NaN,0.0,0.0,NaN,1.0,4.0,5.0,0.0,1.0,2.0,2.0,2.0,0.0,-15.0,0.000,0.000,0.000,0.000,3.9,20.3,11.0,0.0,1.9,6.8,28.6,11.2,8.0,99.0,-10.6,-1.9
4,131410290001,Maurice Harkless,ORL,23:30,6.0,13.0,0.462,2.0,2.0,1.000,0.0,1.0,0.000,1.0,0.0,1.0,0.0,1.0,0.0,0.0,4.0,14.0,-3.0,0.521,0.538,0.154,0.077,4.3,0.0,2.5,0.0,2.2,0.0,0.0,24.0,111.0,107.0,2.4,2.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305727,222304091230,John Butler,POR,22:01,1.0,5.0,0.200,1.0,3.0,0.333,0.0,0.0,NaN,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,3.0,-37.0,0.300,0.300,0.600,0.000,0.0,6.6,2.5,0.0,0.0,0.0,0.0,9.1,58.0,149.0,-14.6,-0.7
305728,222304091230,Chance Comanche,POR,20:47,3.0,5.0,0.600,0.0,0.0,NaN,1.0,4.0,0.250,2.0,1.0,3.0,0.0,0.0,1.0,0.0,0.0,7.0,-29.0,0.518,0.600,0.000,0.800,8.4,7.0,7.9,0.0,0.0,4.9,0.0,13.1,110.0,146.0,-7.6,1.7
305729,222304091230,Jabari Walker,POR,20:44,4.0,6.0,0.667,0.0,2.0,0.000,1.0,2.0,0.500,0.0,3.0,3.0,0.0,0.0,0.0,2.0,0.0,9.0,-29.0,0.654,0.667,0.333,0.333,0.0,21.0,7.9,0.0,0.0,0.0,22.5,17.2,89.0,147.0,-9.8,2.6
305730,222304091230,Drew Eubanks,POR,Did Not Dress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305731,222304091230,Cam Reddish,POR,Did Not Dress,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
game_ids = list(game_info['game_id'].unique())
gid = 222304091230

In [ ]:
# query = f'''
# SELECT game_id, player, team FROM player_stats
# WHERE game_id = {gid}
# '''
# ss = pd.read_sql(query, con=conn)
# ss

In [ ]:
# query = f'''
# SELECT * FROM player_stats
# WHERE game_id = {gid}
# '''
# gid_test = pd.read_sql(query, con=conn)
# gid_test

In [ ]:
# drop unecessary rows and columns
raw_ps = player_stats[player_stats['MP'] != 'Did Not Dress']
raw_ps.reset_index(inplace=True, drop=True)
raw_ps.drop(['MP', 'ORtg', 'DRtg', 'BPM'], axis=1, inplace=True)

In [ ]:
for gid in game_ids:
    # current players df
    current_players = list(raw_ps['player'][raw_ps['game_id'] == gid])
    curr_ps = test_ps[test_ps['player'].isin(current_players)]
    
    a_team = game_info['away_team'][game_info['game_id'] == gid].values[0]
    h_team = game_info['home_team'][game_info['game_id'] == gid].values[0]

In [ ]:
current_players = list(raw_ps['player'][raw_ps['game_id'] == gid])
curr_ps = test_ps[test_ps['player'].isin(current_players)]

In [ ]:
a_team = game_info['away_team'][game_info['game_id'] == gid].values[0]
h_team = game_info['home_team'][game_info['game_id'] == gid].values[0]

# need to get avg_columns names as global var before starting loops
# actual team_agg_df needs to be inside team loops

# remove inactive players
ps_df = player_stats[player_stats['MP'] != 'Did Not Dress']
ps_df.reset_index(inplace=True, drop=True)
# drop unecessary columns
ps_df.drop(['MP', 'ORtg', 'DRtg', 'BPM'], axis=1, inplace=True)
# create list of column names for player/team averages
avg_columns = [column for column in ps_df.columns[1:3]] + [f'{column}_avg' for column in ps_df.columns[3:]]

# list of active away/home players from current game
current_players = list(ps_df['player'][ps_df['game_id'] == gid])
current_a_players = list(ps_df['player'][(ps_df['game_id'] == gid) & (ps_df['team'] == a_team)])
current_h_players = list(ps_df['player'][(ps_df['game_id'] == gid) & (ps_df['team'] == h_team)])
# current players all games
curr_ps = ps_df[ps_df['player'].isin(current_players)]

# for team in game: # need to clarify where these variables are coming from
#     team_past_n_games_df = pd.DataFrame(columns=avg_columns)

In [ ]:
def calc_player_averages(current_player_stats, n_games, roster):
    '''
    Takes a list of player names and calculates the player averages over past n number of games.
    
    Input:
    current_player_stats: a dataframe with game stats for all current players in roster
    n_games: the number of past games to include when averaging
    roster: list of player names
    
    Output: a dataframe with all player averages
    '''
    
    curr_ps = current_player_stats
    team_past_n_games_df = pd.DataFrame(columns=avg_columns)
    
    for player in roster:
        
        player_df = curr_ps[curr_ps['player'] == player].reset_index(drop=True)

        p_idx = player_df.index[player_df['game_id'] == gid].tolist()[0]
        past_n_games = player_df.loc[(p_idx-n_games):(p_idx-1)]

        name = player_df['player'].iloc[p_idx]
        team = player_df['team'].iloc[p_idx]

        FG_avg = past_n_games['FG'].mean()
        FGA_avg = past_n_games['FGA'].mean()
        FGp_avg = FG_avg/FGA_avg
        _3P_avg = past_n_games['3P'].mean()
        _3PA_avg = past_n_games['3PA'].mean()
        _3Pp_avg = _3P_avg/_3PA_avg
        FT_avg = past_n_games['FT'].mean()
        FTA_avg = past_n_games['FTA'].mean()
        FTp_avg = FT_avg/FTA_avg
        ORB_avg = past_n_games['ORB'].mean()
        DRB_avg = past_n_games['DRB'].mean()
        TRB_avg = past_n_games['TRB'].mean()
        AST_avg = past_n_games['AST'].mean()
        STL_avg = past_n_games['STL'].mean()
        BLK_avg = past_n_games['BLK'].mean()
        TOV_avg = past_n_games['TOV'].mean()
        PF_avg = past_n_games['PF'].mean()
        PTS_avg = past_n_games['PTS'].mean()
        PM_avg = past_n_games['PM'].mean()
        TSp_avg = PTS_avg / (2*(FGA_avg + (0.44*FTA_avg)))
        _2P_avg = FG_avg - _3P_avg
        eFGp_avg = (_2P_avg + 1.5*_3P_avg) / FGA_avg
        _3PAr_avg = _3PA_avg / FGA_avg
        FTr_avg = FTA_avg / FGA_avg
        ORBp_avg = past_n_games['ORBp'].mean()
        DRBp_avg = past_n_games['DRBp'].mean()
        TRBp_avg = past_n_games['TRBp'].mean()
        ASTp_avg = past_n_games['ASTp'].mean()
        STLp_avg = past_n_games['STLp'].mean()
        BLKp_avg = past_n_games['BLKp'].mean()
        TOVp_avg = past_n_games['TOVp'].mean()
        USGp_avg = past_n_games['USGp'].mean()
        PIE_avg = past_n_games['PIE'].mean()

        t_idx = team_past_n_games_df.shape[0]
        team_past_n_games_df.loc[t_idx] = [name, team, FG_avg, FGA_avg, FGp_avg, _3P_avg, _3PA_avg, _3Pp_avg, FT_avg, FTA_avg, FTp_avg,
                                           ORB_avg, DRB_avg, TRB_avg, AST_avg, STL_avg, BLK_avg, TOV_avg, PF_avg, PTS_avg, PM_avg,
                                           TSp_avg, eFGp_avg, _3PAr_avg, FTr_avg, ORBp_avg, DRBp_avg, TRBp_avg, ASTp_avg, STLp_avg,
                                           BLKp_avg, TOVp_avg, USGp_avg, PIE_avg]
        
    return team_past_n_games_df

In [ ]:
team_past_10 = calc_player_averages(curr_ps, 10, current_a_players)
team_past_10

In [ ]:
def calc_team_totals(player_avgs_df, n_games):
    
    team_past_n_games_df = player_avgs_df
    team_sum_df = pd.DataFrame(columns=avg_columns[1:])

    team = team_past_n_games_df['team'].iloc[0]
    FG_avg = team_past_n_games_df['FG_avg'].sum()
    FGA_avg = team_past_n_games_df['FGA_avg'].sum()
    FGp_avg = FG_avg/FGA_avg
    _3P_avg = team_past_n_games_df['3P_avg'].sum()
    _3PA_avg = team_past_n_games_df['3PA_avg'].sum()
    _3Pp_avg = _3P_avg/_3PA_avg
    FT_avg = team_past_n_games_df['FT_avg'].sum()
    FTA_avg = team_past_n_games_df['FTA_avg'].sum()
    FTp_avg = FT_avg/FTA_avg
    ORB_avg = team_past_n_games_df['ORB_avg'].sum()
    DRB_avg = team_past_n_games_df['DRB_avg'].sum()
    TRB_avg = team_past_n_games_df['TRB_avg'].sum()
    AST_avg = team_past_n_games_df['AST_avg'].sum()
    STL_avg = team_past_n_games_df['STL_avg'].sum()
    BLK_avg = team_past_n_games_df['BLK_avg'].sum()
    TOV_avg = team_past_n_games_df['TOV_avg'].sum()
    PF_avg = team_past_n_games_df['PF_avg'].sum()
    PTS_avg = team_past_n_games_df['PTS_avg'].sum()
    PM_avg = team_past_n_games_df['PM_avg'].sum()
    TSp_avg = PTS_avg / (2*(FGA_avg + (0.44*FTA_avg)))
    _2P_avg = FG_avg - _3P_avg
    eFGp_avg = (_2P_avg + 1.5*_3P_avg) / FGA_avg
    _3PAr_avg = _3PA_avg / FGA_avg
    FTr_avg = FTA_avg / FGA_avg
    ORBp_avg = team_past_n_games_df['ORBp_avg'].mean()
    DRBp_avg = team_past_n_games_df['DRBp_avg'].mean()
    TRBp_avg = team_past_n_games_df['TRBp_avg'].mean()
    ASTp_avg = team_past_n_games_df['ASTp_avg'].mean()
    STLp_avg = team_past_n_games_df['STLp_avg'].mean()
    BLKp_avg = team_past_n_games_df['BLKp_avg'].mean()
    TOVp_avg = team_past_n_games_df['TOVp_avg'].mean()
    USGp_avg = team_past_n_games_df['USGp_avg'].mean()
    PIE_avg = team_past_n_games_df['PIE_avg'].sum()
    
    ts_idx = team_sum_df.shape[0]
    team_sum_df.loc[ts_idx] = [team, FG_avg, FGA_avg, FGp_avg, _3P_avg, _3PA_avg, _3Pp_avg, FT_avg, FTA_avg, FTp_avg,
                               ORB_avg, DRB_avg, TRB_avg, AST_avg, STL_avg, BLK_avg, TOV_avg, PF_avg, PTS_avg, PM_avg,
                               TSp_avg, eFGp_avg, _3PAr_avg, FTr_avg, ORBp_avg, DRBp_avg, TRBp_avg, ASTp_avg, STLp_avg,
                               BLKp_avg, TOVp_avg, USGp_avg, PIE_avg]
    
    return team_sum_df

In [ ]:
team_agg_df = calc_team_totals(team_past_10, 10)
team_agg_df

In [ ]:
curr_ps

In [ ]:
team_past_n_games_df = pd.DataFrame(columns=avg_columns)

for player in current_a_players:
    player_df = curr_ps[curr_ps['player'] == player].reset_index(drop=True)

    p_idx = player_df.index[player_df['game_id'] == gid].tolist()[0]
    past_n_games = player_df.loc[(p_idx-10):(p_idx-1)]

    name = player_df['player'].iloc[p_idx]
    team = player_df['team'].iloc[p_idx]

    FG_avg = past_n_games['FG'].mean()
    FGA_avg = past_n_games['FGA'].mean()
    FGp_avg = FG_avg/FGA_avg
    _3P_avg = past_n_games['3P'].mean()
    _3PA_avg = past_n_games['3PA'].mean()
    _3Pp_avg = _3P_avg/_3PA_avg
    FT_avg = past_n_games['FT'].mean()
    FTA_avg = past_n_games['FTA'].mean()
    FTp_avg = FT_avg/FTA_avg
    ORB_avg = past_n_games['ORB'].mean()
    DRB_avg = past_n_games['DRB'].mean()
    TRB_avg = past_n_games['TRB'].mean()
    AST_avg = past_n_games['AST'].mean()
    STL_avg = past_n_games['STL'].mean()
    BLK_avg = past_n_games['BLK'].mean()
    TOV_avg = past_n_games['TOV'].mean()
    PF_avg = past_n_games['PF'].mean()
    PTS_avg = past_n_games['PTS'].mean()
    PM_avg = past_n_games['PM'].mean()
    TSp_avg = PTS_avg / (2*(FGA_avg + (0.44*FTA_avg)))
    _2P_avg = FG_avg - _3P_avg
    eFGp_avg = (_2P_avg + 1.5*_3P_avg) / FGA_avg
    _3PAr_avg = _3PA_avg / FGA_avg
    FTr_avg = FTA_avg / FGA_avg
    ORBp_avg = past_n_games['ORBp'].mean()
    DRBp_avg = past_n_games['DRBp'].mean()
    TRBp_avg = past_n_games['TRBp'].mean()
    ASTp_avg = past_n_games['ASTp'].mean()
    STLp_avg = past_n_games['STLp'].mean()
    BLKp_avg = past_n_games['BLKp'].mean()
    TOVp_avg = past_n_games['TOVp'].mean()
    USGp_avg = past_n_games['USGp'].mean()
    PIE_avg = past_n_games['PIE'].mean()

    t_idx = team_past_n_games_df.shape[0]
    team_past_n_games_df.loc[t_idx] = [name, team, FG_avg, FGA_avg, FGp_avg, _3P_avg, _3PA_avg, _3Pp_avg, FT_avg, FTA_avg, FTp_avg,
                                       ORB_avg, DRB_avg, TRB_avg, AST_avg, STL_avg, BLK_avg, TOV_avg, PF_avg, PTS_avg, PM_avg,
                                       TSp_avg, eFGp_avg, _3PAr_avg, FTr_avg, ORBp_avg, DRBp_avg, TRBp_avg, ASTp_avg, STLp_avg,
                                       BLKp_avg, TOVp_avg, USGp_avg, PIE_avg]

In [ ]:
team_past_n_games_df

In [ ]:
team_sum_df = pd.DataFrame(columns=avg_columns[1:])

team = team_past_n_games_df['team'].iloc[0]
FG_avg = team_past_n_games_df['FG_avg'].sum()
FGA_avg = team_past_n_games_df['FGA_avg'].sum()
FGp_avg = FG_avg/FGA_avg
_3P_avg = team_past_n_games_df['3P_avg'].sum()
_3PA_avg = team_past_n_games_df['3PA_avg'].sum()
_3Pp_avg = _3P_avg/_3PA_avg
FT_avg = team_past_n_games_df['FT_avg'].sum()
FTA_avg = team_past_n_games_df['FTA_avg'].sum()
FTp_avg = FT_avg/FTA_avg
ORB_avg = team_past_n_games_df['ORB_avg'].sum()
DRB_avg = team_past_n_games_df['DRB_avg'].sum()
TRB_avg = team_past_n_games_df['TRB_avg'].sum()
AST_avg = team_past_n_games_df['AST_avg'].sum()
STL_avg = team_past_n_games_df['STL_avg'].sum()
BLK_avg = team_past_n_games_df['BLK_avg'].sum()
TOV_avg = team_past_n_games_df['TOV_avg'].sum()
PF_avg = team_past_n_games_df['PF_avg'].sum()
PTS_avg = team_past_n_games_df['PTS_avg'].sum()
PM_avg = team_past_n_games_df['PM_avg'].sum()
TSp_avg = PTS_avg / (2*(FGA_avg + (0.44*FTA_avg)))
_2P_avg = FG_avg - _3P_avg
eFGp_avg = (_2P_avg + 1.5*_3P_avg) / FGA_avg
_3PAr_avg = _3PA_avg / FGA_avg
FTr_avg = FTA_avg / FGA_avg
ORBp_avg = team_past_n_games_df['ORBp_avg'].mean()
DRBp_avg = team_past_n_games_df['DRBp_avg'].mean()
TRBp_avg = team_past_n_games_df['TRBp_avg'].mean()
ASTp_avg = team_past_n_games_df['ASTp_avg'].mean()
STLp_avg = team_past_n_games_df['STLp_avg'].mean()
BLKp_avg = team_past_n_games_df['BLKp_avg'].mean()
TOVp_avg = team_past_n_games_df['TOVp_avg'].mean()
USGp_avg = team_past_n_games_df['USGp_avg'].mean()
PIE_avg = team_past_n_games_df['PIE_avg'].sum()

In [ ]:
ts_idx = team_sum_df.shape[0]
team_sum_df.loc[ts_idx] = [team, FG_avg, FGA_avg, FGp_avg, _3P_avg, _3PA_avg, _3Pp_avg, FT_avg, FTA_avg, FTp_avg,
                           ORB_avg, DRB_avg, TRB_avg, AST_avg, STL_avg, BLK_avg, TOV_avg, PF_avg, PTS_avg, PM_avg,
                           TSp_avg, eFGp_avg, _3PAr_avg, FTr_avg, ORBp_avg, DRBp_avg, TRBp_avg, ASTp_avg, STLp_avg,
                           BLKp_avg, TOVp_avg, USGp_avg, PIE_avg]

In [ ]:
team_sum_df

In [ ]:
sc_df = curr_ps[curr_ps['player'] == 'Stephen Curry'].reset_index(drop=True)
sc_df

In [ ]:
p_idx = sc_df.index[sc_df['game_id'] == gid].tolist()[0]
p_idx

In [ ]:
sc_df['player'].iloc[p_idx]

In [ ]:
idx = sc_df.index[sc_df['game_id'] == gid].tolist()[0]
past_n_games = sc_df.loc[(idx-10):(idx-1)]
past_n_games

In [ ]:
past_n_games.columns[3:]

In [ ]:
avg_columns = [column for column in past_n_games.columns[1:3]] + [f'{column}_avg' for column in past_n_games.columns[3:]]
team_past_n_games_df = pd.DataFrame(columns=avg_columns)
team_past_n_games_df

In [ ]:
len(avg_columns)

In [ ]:
name = past_n_games['player'].iloc[-1]
team = past_n_games['team'].iloc[-1]

FG_avg = past_n_games['FG'].mean()
FGA_avg = past_n_games['FG'].mean()
FGp_avg = FG_avg/FGA_avg
_3P_avg = past_n_games['3P'].mean()
_3PA_avg = past_n_games['3PA'].mean()
_3Pp_avg = _3P_avg/_3PA_avg
FT_avg = past_n_games['FT'].mean()
FTA_avg = past_n_games['FTA'].mean()
FTp_avg = FT/FTA
ORB_avg = past_n_games['ORB'].mean()
DRB_avg = past_n_games['DRB'].mean()
TRB_avg = past_n_games['TRB'].mean()
AST_avg = past_n_games['AST'].mean()
STL_avg = past_n_games['STL'].mean()
BLK_avg = past_n_games['BLK'].mean()
TOV_avg = past_n_games['TOV'].mean()
PF_avg = past_n_games['PF'].mean()
PTS_avg = past_n_games['PTS'].mean()
PM_avg = past_n_games['PM'].mean()
TSp_avg = PTS_avg / (2*(FGA_avg + (0.44*FTA_avg)))
_2P_avg = FG_avg - _3P_avg
eFGp_avg = (_2P_avg + 1.5*_3P_avg) / FGA_avg
_3PAr_avg = _3PA_avg / FGA_avg
FTr_avg = FTA_avg / FGA_avg
ORBp_avg = past_n_games['ORBp'].mean()
DRBp_avg = past_n_games['DRBp'].mean()
TRBp_avg = past_n_games['TRBp'].mean()
ASTp_avg = past_n_games['ASTp'].mean()
STLp_avg = past_n_games['STLp'].mean()
BLKp_avg = past_n_games['BLKp'].mean()
TOVp_avg = past_n_games['TOVp'].mean()
USGp_avg = past_n_games['USGp'].mean()
PIE_avg = past_n_games['PIE'].mean()

idx = team_past_n_games_df.shape[0]
team_past_n_games_df.loc[idx] = [name, team, FG_avg, FGA_avg, FGp_avg, _3P_avg, _3PA_avg, _3Pp_avg, FT_avg, FTA_avg, FTp_avg,
                                 ORB_avg, DRB_avg, TRB_avg, AST_avg, STL_avg, BLK_avg, TOV_avg, PF_avg, PTS_avg, PM_avg,
                                 TSp_avg, eFGp_avg, _3PAr_avg, FTr_avg, ORBp_avg, DRBp_avg, TRBp_avg, ASTp_avg, STLp_avg,
                                 BLKp_avg, TOVp_avg, USGp_avg, PIE_avg]